### ISSUE TITLE
Unable to discover Palo Alto FW

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#103]
When running discover with admin account, I am getting error as below, Palo Alto FW model 220

Task parameters
{'order': 0, 'enable': False, 'command': '<show><system><info></info></system></show>', 'platform': 'panw_ngfw', 'protocol': 'default', 'template': 'show system info', 'framework': 'xml', 'supported': True}

Details
{'command': '<show><system><info></info></system></show>',
 'enable': False,
 'framework': 'xml',
 'order': 0,
 'platform': 'panw_ngfw',
 'protocol': 'default',
 'supported': True,
 'template': 'show system info'}

Raw output
ERROR CODE 403
<response status = 'error' code = '403'><result><msg>Invalid Credential</msg></result></response>

**Comment by dainok** [comment]
The error is clear: the user you are using is not able to get API.
Pleaase check: https://github.com/dainok/fwadmin/wiki/Firewall-configuration
And also check manually if you can use XML API (wget is sufficient).

**Comment by dietybright** [comment]
Sorry for late, just found out that the password of device on netdoc/discoverable should be API token, not username and password of API access, thank you
