### ISSUE TITLE
Ignore prefix created if same vlue already existed on Netbox

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#107]
I have fixed all prefix duplicate issue after remove those duplicated prefix in mgmt vrf, after re-discovery, Netdoc auto re-create those prefix

**Comment by dainok** [comment]
Prefixes are created based on IP VRF.
Can you double check if duplicated prefixes have different VRFs?

**Comment by dietybright** [comment]
Yes it is different vrf.

When discover mgmt switch, the mgmt IP is belong to mgmt-vrf, then it keep re-create mgmt-vrf

**Comment by dainok** [comment]
Ok, the procedure is:
Update IP address and prefix, setting the right VRF
Delete useless prefixes
Check in the report if everything is fine
Import from ARP table

Check Wiki for additional details.

Let me know if you have issues with this procedure

**Comment by dietybright** [comment]
Hi @dainok ,

I have followed the procedure correctly, the point is when running discovery script periodically , netdoc will import the deleted VRF again

**Comment by dainok** [comment]
Check https://github.com/dainok/netdoc/pull/111

**Comment by dainok** [comment]
I also removed /32 prefixes.
