### ISSUE TITLE
Support for Allied-Telesis switches

### ISSUE THREAD

**Issue by tatumi0726** [dainok/netdoc#114]
Hello, nice to meet you.
I am an infrastructure engineer in Japan.
I have been using netbox and NetDoc for some time now and have found them to be very useful in my work environment.

I am contacting you to ask if it is possible to merge my modified script code.
I have created discoverers, templates and ingestors for Allied-Telesis, a Japanese vendor, and have also modified some of the utils.py.
The code I have created has been embedded in a netbox 3.5.9 + NetDoc 3.5.18 environment and is actually in operation in the environment where I work.
I am not familiar with coding, so the code may be unreadable...

I am not a programmer, so I did not know how to proceed with this kind of procedure, so I am asking for help here first.

If you are able to merge the two, could you please tell me about the procedure to follow?
Thank you in advance.
(Translated by DeepL)

**Comment by dainok** [comment]
Hi @tatumi0726 ! Thank you for your enhancement. Would you please send the file to my email andrea.dainese@pm.me?
I'm happy to integrate them. I need also some output files to avoid errors in the future.

**Comment by tatumi0726** [comment]
Hello, @dainok !
I am very happy to hear back from you so quickly.

Please wait a moment while I send you an email later.

The output file you need should be similar to the one published at the following URL?

https://github.com/dainok/netdoc/tree/master/netdoc/tests/netmiko_cisco_ios/lab1/logs

If it is just the one extracted from the NetDoc logs, it won't take much time.

**Comment by dainok** [comment]
@tatumi0726 correct. I need you set up a lab with all relevant features (IP routing, LLDP, port-channel, OSPF, ARP...) and write a log per each "show" command. I need a log file for all "show" command included in the discoverer.

**Comment by tatumi0726** [comment]
Hello, @dainok
Sorry for taking so long to reply.

Yes sir, I will set up the lab and collect the necessary logs.
Please give me some time, I only have time for this activity on weekends or so...

I will try to work on the following sense of schedule.

- This weekend
Set up the lab and create test code

- Next weekend
Test code execution and logging
If possible, I would like to submit by the end of next week.

**Comment by dainok** [comment]
No worries, take your time.

**Comment by tatumi0726** [comment]
Hello, @dainok

Sorry, it will take another week.
It took us a long time to prepare and test the environment.

We are about 80% done with the testing, so we will be able to contact you next week to let you know the completion.

Thank you for your patience.

**Comment by tatumi0726** [comment]
Hello, @dainok

Sorry for the delay.
I even completed the code test and pushed it to my repository where I forked it.

(Along with the testing, I have moved the AlliedTelesis dependency code from utils.py to Ingestor)

[TEST-CODE_20240211-131417.log](https://github.com/dainok/netdoc/files/14231336/TEST-CODE_20240211-131417.log)
https://github.com/tatumi0726/netdoc/tree/test-allied-telesis

After that, should I have done a pull request?
I apologize for the inconvenience, but I would appreciate your guidance when you are available.

**Comment by dainok** [comment]
Hello @tatumi0726 ,

please create a pull request, then I'll manage checks, tests and merge.
I'll write you if I need additional info.
Thank you for your contribution

Andrea

**Comment by tatumi0726** [comment]
Hello, @dainok

Yes, I will create a pull request later.

We have also modified the template and have once uploaded it below.
https://github.com/tatumi0726/netdoc/tree/test-allied-telesis/netdoc/tests/netmiko_allied_telesis_awplus/lab1/templates

Thank you very much for this great opportunity.

**Comment by dainok** [comment]
Preparing NTC-Templates PR https://github.com/dainok/ntc-templates/tree/add_allied_telesis

**Comment by dainok** [comment]
https://github.com/dainok/netdoc/pull/122
