### ISSUE TITLE
NetDoc is not ingesting data

### ISSUE THREAD

**Issue by nhincaigiem** [dainok/netdoc#115]
netdoc version 0.10.30
netbox 3.4.10
NetDoc.Ingest status pending
I wonder why it's pending 

![image](https://github.com/dainok/netdoc/assets/157591068/cb213ca8-adaf-485c-8866-339fc4f1615d)

![image](https://github.com/dainok/netdoc/assets/157591068/be48a1f4-836d-4d49-92ee-9e9075a9a7d0)

**Comment by nhincaigiem** [comment]
How to view ingest activity log ?

**Comment by dainok** [comment]
Probably you are not starting the RQ component from Netbox.
Mind that I'm not supporting Netbox 3.4 anymore.

**Comment by nhincaigiem** [comment]
@dainok  I am running rq version 1.13.0 .Everything works normally .
Issus :The issue at NetDoc.Ingest is pending .
I followed the instructions at https://github.com/dainok/netdoc/wiki/NetBox-with-NetDoc-installation
I tried version netbox 3.5.8 but still the same problem
Discover running
![image](https://github.com/dainok/netdoc/assets/157591068/cac72d0a-7238-495b-a5da-9e5ed72c7269)

![image](https://github.com/dainok/netdoc/assets/157591068/cd429123-3fec-4072-95c2-803ed6ee0f15)

**Comment by nhincaigiem** [comment]
NetDoc.Ingest job log
![image](https://github.com/dainok/netdoc/assets/157591068/2955b86c-e54a-43a9-8131-8a531af273ba)

**Comment by dainok** [comment]
I think you are using an unsupported mix of netdoc and netbox versions. Please upgrade both NetBox and NetDoc to 3.5.

**Comment by nhincaigiem** [comment]
I have updated to the latest version and it runs successfully
But when I import the Cisco WS-C6503-E device, I get the following error message
![image](https://github.com/dainok/netdoc/assets/157591068/51f844ef-4374-412e-b674-3f90a5573a80)

**Comment by dainok** [comment]
Please attach log 479

**Comment by nhincaigiem** [comment]
Can you show me where log 479 is located?
![image](https://github.com/dainok/netdoc/assets/157591068/94d7f792-a8b0-4d1a-b421-8ffda4536a82)

**Comment by dainok** [comment]
NetDoc -> Logs -> 470 -> Export (top-right). A JSON is downloaded, send it to me here or via email, as you wish.

**Comment by nhincaigiem** [comment]
[479.json](https://github.com/dainok/netdoc/files/14309460/479.json)
Is this file correct?

**Comment by dainok** [comment]
@nhincaigiem in the show ver output I see a space before the hostname:

``` XXXX-XXX_XXX uptime is 9 weeks```

Can you confirm?

**Comment by nhincaigiem** [comment]
That's right, there is a space before the server name

**Comment by dainok** [comment]
Fixed in [3.5.20](https://github.com/dainok/netdoc/releases/tag/3.5.20)
