### ISSUE TITLE
Nornir inventory is empty

### ISSUE THREAD

**Issue by stefan968** [dainok/netdoc#127]
I'm new to Netbox so maybe I'm doing something wrong. When I run a discovery I see this error in the logs:

[root@localhost ~]# journalctl -u netbox-rq -f
Apr 17 21:37:12 localhost.localdomain python3[37333]: dict_keys([])
Apr 17 21:37:12 localhost.localdomain python3[37333]: Nornir inventory is empty
Apr 17 21:37:12 localhost.localdomain python3[37333]: 19:37:12 default: Job OK (17a54d3b-562e-4150-bb8e-0a7392dbb378)
Apr 17 21:37:12 localhost.localdomain python3[37333]: 19:37:12 Result is kept for 500 seconds
Apr 17 21:42:42 localhost.localdomain python3[1796]: 19:42:42 default: extras.scripts.run_script(data={'discoverables': [<Discoverable: 192.168.121.1 via netmiko_cisco_ios>]}, job=<Job: 595d3158-4d49-444d-937a-5f8d022b73d9>, request=<utilities.utils.NetBoxFakeRequest object at 0x7f8500c79100>) (595d3158-4d49-444d-937a-5f8d022b73d9)
Apr 17 21:42:42 localhost.localdomain python3[37421]: ['192.168.121.1']
Apr 17 21:42:42 localhost.localdomain python3[37421]: dict_keys([])
Apr 17 21:42:42 localhost.localdomain python3[37421]: Nornir inventory is empty
Apr 17 21:42:42 localhost.localdomain python3[37421]: 19:42:42 default: Job OK (595d3158-4d49-444d-937a-5f8d022b73d9)
Apr 17 21:42:42 localhost.localdomain python3[37421]: 19:42:42 Result is kept for 500 seconds

**Comment by dainok** [comment]
See the FAQ: https://github.com/dainok/netdoc/wiki/FAQ#nornir-inventory-is-empty

**Comment by stefan968** [comment]
Oh wow thanks overlooked that one. Getting a new error though:
An exception occurred: TypeError: Device() got unexpected keyword arguments: 'device_role_id'

Traceback (most recent call last):
  File "/opt/netbox-3.7.3/netbox/extras/scripts.py", line 512, in _run_script
    script.output = script.run(data=data, commit=commit)
  File "/opt/netbox-3.7.3/netbox/scripts/netdoc_scripts.py", line 357, in run
    log_ingest(log)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 407, in log_ingest
    module.ingest(log)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/ingestors/netmiko_cisco_ios_hostname.py", line 38, in ingest
    device_o = device.create(**data)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/schemas/device.py", line 108, in create
    obj = utils.object_create(Device, **kwargs)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 931, in object_create
    return model_o.objects.create(**kwargs)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
  File "/opt/netbox-3.7.3/netbox/utilities/tracking.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: Device() got unexpected keyword arguments: 'device_role_id'

**Comment by dainok** [comment]
I think you are using an unsupported combination of Netbox / NetDoc.
Please mind that: NetDoc 3.5.x requires NetBox 3.5.x

**Comment by stefan968** [comment]
Ok thanks I installed netbox 3.5.8 but now I'm getting another error:

Apr 24 19:43:22 astdcaman16 systemd[1]: Started NetBox Request Queue Worker.
Apr 24 19:43:25 astdcaman16 python3[23096]: Traceback (most recent call last):
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/netbox/manage.py", line 10, in <module>
Apr 24 19:43:25 astdcaman16 python3[23096]:     execute_from_command_line(sys.argv)
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_>
Apr 24 19:43:25 astdcaman16 python3[23096]:     utility.execute()
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
Apr 24 19:43:25 astdcaman16 python3[23096]:     django.setup()
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
Apr 24 19:43:25 astdcaman16 python3[23096]:     apps.populate(settings.INSTALLED_APPS)
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
Apr 24 19:43:25 astdcaman16 python3[23096]:     app_config.ready()
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/__init__.py", line 69, in ready
Apr 24 19:43:25 astdcaman16 python3[23096]:     jobs_ds_o.sync()  # Load files
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox-3.5.8/netbox/core/models/data.py", line 202, in sync
Apr 24 19:43:25 astdcaman16 python3[23096]:     post_sync.send(sender=self.__class__, instance=self)
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
Apr 24 19:43:25 astdcaman16 python3[23096]:     return [
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
Apr 24 19:43:25 astdcaman16 python3[23096]:     (receiver, receiver(signal=self, sender=sender, **named))
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox-3.5.8/netbox/core/signals.py", line 21, in auto_sync
Apr 24 19:43:25 astdcaman16 python3[23096]:     autosync.object.sync(save=True)
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox-3.5.8/netbox/netbox/models/features.py", line 478, in sync
Apr 24 19:43:25 astdcaman16 python3[23096]:     self.sync_data()
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox-3.5.8/netbox/core/models/files.py", line 79, in sync_data
Apr 24 19:43:25 astdcaman16 python3[23096]:     self.data_file.write_to_disk(self.full_path, overwrite=True)
Apr 24 19:43:25 astdcaman16 python3[23096]:   File "/opt/netbox-3.5.8/netbox/core/models/data.py", line 330, in write_to_disk
Apr 24 19:43:25 astdcaman16 python3[23096]:     with open(path, 'wb+') as new_file:
Apr 24 19:43:25 astdcaman16 python3[23096]: PermissionError: [Errno 13] Permission denied: '/opt/netbox-3.5.8/netbox/scripts/netdoc_scripts.py'
Apr 24 19:43:26 astdcaman16 systemd[1]: netbox-rq.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 19:43:26 astdcaman16 systemd[1]: netbox-rq.service: Failed with result 'exit-code'.

**Comment by stefan968** [comment]
Although there's this error NetDoc is working now!

**Comment by dainok** [comment]
`Permission denied` means permissions are wrong on your Linux subsystem.
