### ISSUE TITLE
Issue Connecting to CIsco ASA Firewall

### ISSUE THREAD

**Issue by BSautter** [dainok/netdoc#129]
Could You please let me know how to turn on better debugging?  The discover logs just say that the connection was refused, but Putty from the same machine connects with no issues.  I do not want to open this as a bug, until I can gather more information to present.

Thank you for your support.

**Comment by dainok** [comment]
Hi Cisco ASA is not supported yet, so I don't know if you are developing a patch or if you are trying to discover ASA using a different template.
Connection refused means RST received by Netbox, so I suggest to check with tcpdump. BTW it won't work because there is no Cisco ASA template.

**Comment by BSautter** [comment]
Thank you for your help Andrea,  I was trying to do a discover on the ASA.  I did not know that the ASA was not supported.  I will continue on with a manual configuration.

Thank you again.
