### ISSUE TITLE
Ability to re-run discovery on failed connection/1 log devices

### ISSUE THREAD

**Issue by andyb2000** [dainok/netdoc#13]
I'm seeing on my bulk run some devices seem to get timeouts/unable to connect first time round. If I search for them and run a single discover they succeed (suspect too many concurrent connections to device, etc).

On those devices, netdoc shows:
ID	Created	Discoverable	Device	Command	Order	Configuration	Supported	Success	Parsed	Ingested	
135576	2023-06-13 02:55	194.x.x.x via netmiko_cisco_ios	—	show running-config | include hostname	0	✘	✔	✘	✘	✘	

I'm going to look at creating a script/option to detect a discoverable with only 1 failed hostname discovery job so that I can do a bulk re-run (unless any better suggestions?)

**Comment by andyb2000** [comment]
(more of a feature, but I can't add a label to the repo)

**Comment by dainok** [comment]
Can you please check in discoverable if you have a last_discovered_at date?

Seems to me a bug not a feature. last_discovered_at should help but maybe it's not working as expected.

**Comment by andyb2000** [comment]
Oh interesting, yes you're right it shows a last_discovered despite it clearly failing:

![image](https://github.com/dainok/netdoc/assets/1208595/359691b2-9fd4-4f06-bf5f-0e6c354f1a0c)

**Comment by dainok** [comment]
Bug confirmed. Should check Nornir API.

**Comment by dainok** [comment]
@andyb2000 could you check https://github.com/dainok/netdoc/pull/14

**Comment by andyb2000** [comment]
Testing now (Have had to re-base my changes and do a lot to merge any custom stuff I've done, so taking time to get back on track to be able to pull from master!)

Will report back asap on this and others
