### ISSUE TITLE
not working in virtual environment

### ISSUE THREAD

**Issue by pirona** [dainok/netdoc#13]
Hello,

I followed official netbox install process, the yours and I got this error : 

`Nov 15 06:50:42 netbox python3[2988]: django.core.exceptions.ImproperlyConfigured: Unable to import plugin netdoc: Module not found. Check that the plugin module has been installed within the correct Python environment.`

I tried to simply `pip install netdoc` in my venv but it doesn't help.

How can I work this out ?

**Comment by dainok** [comment]
You must install netdoc in the same venv used by netbox.
