### ISSUE TITLE
Interface name normalization

### ISSUE THREAD

**Issue by a084ed22** [dainok/netdoc#2]
Hello,

first of all, thank you for creating this plugin, it is being helpful in my company's effort to better document infrastructure.

I'm however noticing some issues related to Cisco's rendering of names in commands leading to short interface names - and therefore redundant interfaces, one stemming from our use of templates pre-populating them for each device, and one from this plugin:

![image](https://user-images.githubusercontent.com/90847254/189116776-1e54e5a7-c0ab-4d41-9efb-a797bf73dc67.png)

would it be possible to ask for a normalization step to have standardize on either the long format or the short format for all interfaces? As far as we've seen, the short form is fairly inconsistent across different releases and models, so it might be more sensible to opt for the full name format.

**Comment by dainok** [comment]
Before answering; I need to explain how shortname is used. In many outputs, interface name is displayed in different ways, sometimes GigabitEthernet1/0/1, sometimes Gi1/0/1... and so on. I counted at least 3 different ways on show ip route/mac addresses/arp/interfaces/cdp/lldp.... To avoid duplicates I decided to shorten interfaces and use shortname as interface ID.
If you are using netdoc in a blank netbox installation, when you are discovering via CDP/LLDP you will see the correct shortname, and a wrong name. Once you are discovering each device, you should see the correct interface name too.

In your setup, I guess you could fill the shortname on the interfaces you consider valid. I know, that's not a good solution, but remember, it's alpha :)

BTW thank you for your report, I'm thinking that a partial discovery could fix your scenario.
In this phase I'm collecting feedback from users, so I can clear my ideas.

**Comment by a084ed22** [comment]
Apologies, I haven't had the chance to get it tested until now. Priming the label field with the proposed script seem to result in no new interfaces being created.

**Comment by dainok** [comment]
Thank you for the feedback. In the future I'll find a better way to implement that trick.
