### ISSUE TITLE
discovery config

### ISSUE THREAD

**Issue by mamingzhi945** [dainok/netdoc#23]
Ingest time is too long, more than 10 hours have not been completed, timed out. I would like to know that there are configuration items to delete some found objects for the data necessary to generate l2 and l3 diagrams.

**Comment by dainok** [comment]
I think you are testing NetDoc on a very large network.

If everything is working ok, ingest phase should spanwn a job after 50 logs, so you don't have a huge job ingesting everything. (please check)

You can also skip some commands, like show ip route, arp, mac-address table.

You can discover (and ingest) a subset of devices, and add more devices step by step.

**Comment by mamingzhi945** [comment]
i know
