### ISSUE TITLE
[Question] Discovery run on update vlan, etc

### ISSUE THREAD

**Issue by PVM-NL** [dainok/netdoc#25]
Hi,

Thanks for this plugin!

I wonder if your plugin also update configuration when this change on switch, that it updates the existing configuration on netbox.
When configuring the plugin and did a re-discover, I notice that it creates a new object again for example a vlan even when it is already in netbox, so it only needs to update the description/name. It also creates all 4096 vlans while they are not in use by the device.

Is it possible that it updates existing configuration inside netbox and maybe even have a update job when device is discover?
Or I might do something wrong?

Also notice that added device(type)  Manufacturer is Cisco Systems and not matching Cisco from device-library from netbox.
Does it uses the devicetypes when they are already provided ?

**Comment by dainok** [comment]
1) it is not expected, current data should be updated, unless you discover a bug. Mind that netbox is using group of vlans associated to interfaces, so it's more complicated. Can you post a step by step procedure to replicate the issue?

2) I'm using the string coming from "show version". In my lab I think you are referring to https://github.com/netbox-community/devicetype-library, which I wasn't aware of. I'm giving it a deeper look.

Mind that this is an alpha version which is helping me how netdoc is working on real infrastructure and how I can improve it. If you have additional advises, you are welcomed.

**Comment by PVM-NL** [comment]
I think i found why he created all the vlans as of the following:

![image](https://user-images.githubusercontent.com/120473446/211560369-89e1ee59-14ff-4db1-a97f-06f477c8afe5.png)

**Comment by dainok** [comment]
Ok thank you. I guess that because you are using a trunk with all VLANs, the script create all VLAN even if they are not configured. I'll double check that.

**Comment by PVM-NL** [comment]
Yes correct. 

Other one was updating the configuration time from time is that somewhere scheduled or when something is changed on the device that the plugin runs again? You mean it should do that right?

**Comment by dainok** [comment]
Currenlty is manual. In the future (hopefully) the user could schedule the discovery verifying which information will be updated.

**Comment by dainok** [comment]
NetDoc has been cleaned a lot and better integrated with Netbox.
Discovery scripts are now using Netbox infrastructure and they can be scheduled on Other -> Scripts or Other -> Reports.

NetDoc is not creating anymore 4094 VLANs, it's just using trunk-all flag.
