### ISSUE TITLE
Add support for Linux boxes

### ISSUE THREAD

**Issue by amdei** [dainok/netdoc#3]
Are there any plans to add support of discovery bare Linux boxes (e.g. Debian)?

I could help with that, as experienced in both Linux administration and Python programming.
But I have no clue where to start, how to debug solutions and there is no contribution guide, as I may see.

Any suggestions on where to start?

**Comment by dainok** [comment]
Which output do you like to capture?
route -n, ifconfig, arp -n... what else?

**Comment by amdei** [comment]
As a bare minimum I would be glad to capture:

1. List of interfaces: `ip link`
2. ARP table: `arp -en`
3. Default routing table: `ip route show`
4. List of routing tables (aka VRFs): `cat /etc/iproute2/rt_tables` (parsing required :-( )
5. Routing table per "VRFs": `ip route show table {vrf}`

**Comment by dainok** [comment]
May I ask you to paste here few lines of each output? (especially VRF, I don't have that conf in my systems)

**Comment by amdei** [comment]
Sure!

BTW:
>  (especially VRF, I don't have that conf in my systems)

You may want to install `iproture2` package to the system, it one available for your distro - it should appear then.

Sample commands output from my machine:

1. `ip link`
```
# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:4d:64:2a brd ff:ff:ff:ff:ff:ff
    altname enp2s1
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:76:7f:aa:93 brd ff:ff:ff:ff:ff:ff

```

2. `arp -en`
```
# arp -en
Address                  HWtype  HWaddress           Flags Mask            Iface
192.168.85.2             ether   a0:36:9f:3c:17:ec   C                     ens33
192.168.85.129           ether   d0:17:c2:92:eb:38   C                     ens33
192.168.85.134           ether   00:50:56:8b:1a:05   C                     ens33
192.168.85.1             ether   00:00:5e:00:01:55   C                     ens33

```

3. `ip route show`
```
# ip route show
default via 192.168.85.1 dev ens33
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.85.0/24 dev ens33 proto kernel scope link src 192.168.85.184

```

4. List of routing tables (aka VRFs) !PARSING REQUIRED!: 
```
# cat /etc/iproute2/rt_tables
#
# reserved values
#
255     local
254     main
253     default
0       unspec
#
# local
#
#1      inr.ruhep

3983 NGRT_3983
3984 NGRT_3984
```
5. Routing table per "VRFs": `ip route show table {vrf}`

```
# ip route show table local
broadcast 127.0.0.0 dev lo proto kernel scope link src 127.0.0.1
local 127.0.0.0/8 dev lo proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo proto kernel scope link src 127.0.0.1
broadcast 172.17.0.0 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
local 172.17.0.1 dev docker0 proto kernel scope host src 172.17.0.1
broadcast 172.17.255.255 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
broadcast 192.168.85.0 dev ens33 proto kernel scope link src 192.168.85.184
local 192.168.85.184 dev ens33 proto kernel scope host src 192.168.85.184
broadcast 192.168.85.255 dev ens33 proto kernel scope link src 192.168.85.184

```

**Comment by dainok** [comment]
@amdei I figured out how I can approach this task. Before I need an additional output from you. I  found that:
ip route show and ip route show table main have the same output.

Do you have an output from a VRF excluding local/main/default/unspec?

I would include only:
ip route show table main
ip route show table vrfa

What do you think about?

**Comment by dainok** [comment]
Moreover, isn't better to use "ip vrf show" instead of "/etc/iproute2/rt_tables"?
The file in /etc is like a "startup config", the "ip vrf show" is more like "show running".

**Comment by dainok** [comment]
@amdei check if those templates can work for you. After I can implement the netdoc integration.

**Comment by dainok** [comment]
Depend on https://github.com/networktocode/ntc-templates/pull/1193
