### ISSUE TITLE
RoutingTable URL NoReverseMatch

### ISSUE THREAD

**Issue by Lurick73** [dainok/netdoc#33]
When attempting to access the following portion of the NetDoc Tables I get the below error:
netbox-url.com/plugins/netdoc/routingtable/
```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'routingtable' not found. 'routingtable' is not a valid view function or pattern name.

Python version: 3.10.6
NetBox version: 3.4.10
```

I didn't see anything else around with a similar error and not exactly sure what might have triggered it.

**Comment by dainok** [comment]
Update to latest, I fixed this morning.

**Comment by Lurick73** [comment]
Confirmed fixed, thanks!
