### ISSUE TITLE
Really big routing table timeouts

### ISSUE THREAD

**Issue by andyb2000** [dainok/netdoc#34]
If a Cisco router has the full BGP table in, it seems to choke on discovery.

Discovering the router (Cisco ASR9010) looks fine until it gets to:
python3[14346]: ---- {"command": "show ip route", "template": "show ip route", "enable": true, "order": 128} ** changed : False  INFO

Changing this to
"show ip route connected"
Would be safer to avoid learning BGP/OSPF learnt routes? (Or somehow having it as an option to avoid discovering too many routes and causing the issue)

Initially I increased the timeout to avoid the script getting a timeout (configuration.py for netbox):
RQ_DEFAULT_TIMEOUT = 1900

But this causes the error (after part of the routing table is shown in logs, about 2 mins later it shows):
`Mar 16 16:41:53 srvr-0040b606 python3[14346]: No Netmiko HPE Comware device found
Mar 16 16:41:53 srvr-0040b606 python3[14346]: No Netmiko Linux device found
Mar 16 16:42:02 srvr-0040b606 python3[14468]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_xr_show_lldp_neighbors`
Mar 16 16:42:02 srvr-0040b606 python3[14468]: ```
Mar 16 16:42:02 srvr-0040b606 python3[14468]: Traceback (most recent call last):
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 230, in log_ingest
Mar 16 16:42:02 srvr-0040b606 python3[14468]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
Mar 16 16:42:02 srvr-0040b606 python3[14468]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
Mar 16 16:42:02 srvr-0040b606 python3[14468]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_xr_show_lldp_neighbors'
Mar 16 16:42:02 srvr-0040b606 python3[14468]: The above exception was the direct cause of the following exception:
Mar 16 16:42:02 srvr-0040b606 python3[14468]: Traceback (most recent call last):
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 16 16:42:02 srvr-0040b606 python3[14468]:     script.output = script.run(data=data, commit=commit)
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 273, in run
Mar 16 16:42:02 srvr-0040b606 python3[14468]:     log_ingest(log)
Mar 16 16:42:02 srvr-0040b606 python3[14468]:   File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 232, in log_ingest
Mar 16 16:42:02 srvr-0040b606 python3[14468]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 16 16:42:02 srvr-0040b606 python3[14468]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_xr_show_lldp_neighbors
Mar 16 16:42:02 srvr-0040b606 python3[14468]: ```
Mar 16 16:42:02 srvr-0040b606 python3[14468]: Exception raised during script execution: Ingestor not found for netmiko_cisco_xr_show_lldp_neighbors

`

Any suggestions initially?

**Comment by dainok** [comment]
Because I released a lot of fixes, please be sure you are using the last NetDoc version:

/opt/netbox/venv/bin/pip freeze | grep netdoc

You should see 0.9.32.
Update, restart (also the scheduler, or do a full reboot), delete old logs and rescan.

**Comment by andyb2000** [comment]
Cool, thanks for quick reply. Confirmed updated:
# /opt/netbox/venv/bin/pip freeze | grep netdoc
netdoc==0.9.32

Updated/deleted logs and running a rescan, looks like it choked at the same point, retrieved part of the huge routing table then:

`
Mar 16 17:10:51 srvr-0040b606 systemd-journald[518]: [🡕] Suppressed 873314 messages from netbox-rq.service
Mar 16 17:10:51 srvr-0040b606 python3[14870]: No Netmiko HPE Comware device found
Mar 16 17:10:51 srvr-0040b606 python3[14870]: No Netmiko Linux device found
Mar 16 17:11:00 srvr-0040b606 python3[14897]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_xr_show_lldp_neighbors`
Mar 16 17:11:00 srvr-0040b606 python3[14897]: ```
Mar 16 17:11:00 srvr-0040b606 python3[14897]: Traceback (most recent call last):
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 230, in log_ingest
Mar 16 17:11:00 srvr-0040b606 python3[14897]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
Mar 16 17:11:00 srvr-0040b606 python3[14897]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
Mar 16 17:11:00 srvr-0040b606 python3[14897]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_xr_show_lldp_neighbors'
Mar 16 17:11:00 srvr-0040b606 python3[14897]: The above exception was the direct cause of the following exception:
Mar 16 17:11:00 srvr-0040b606 python3[14897]: Traceback (most recent call last):
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 16 17:11:00 srvr-0040b606 python3[14897]:     script.output = script.run(data=data, commit=commit)
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 273, in run
Mar 16 17:11:00 srvr-0040b606 python3[14897]:     log_ingest(log)
Mar 16 17:11:00 srvr-0040b606 python3[14897]:   File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 232, in log_ingest
Mar 16 17:11:00 srvr-0040b606 python3[14897]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 16 17:11:00 srvr-0040b606 python3[14897]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_xr_show_lldp_neighbors
Mar 16 17:11:00 srvr-0040b606 python3[14897]: ```
Mar 16 17:11:00 srvr-0040b606 python3[14897]: Exception raised during script execution: Ingestor not found for netmiko_cisco_xr_show_lldp_neighbors
`

So, thinking, this isn't sticking on the large routing table as first thought, the module for "netmiko_cisco_xr_show_lldp_neighbors" missing?
How can I check/install that module?
Thank you!

**Comment by andyb2000** [comment]
Closing as pull request submitted to resolve this and others.
