### ISSUE TITLE
[Issue] NX-OS parser script wrongly parses mac address as IP address

### ISSUE THREAD

**Issue by svestenik** [dainok/netdoc#37]
While trying to discover a Nexus 3048 switch running NXOS version 9.3, NX-OS parser hits a problem:

```
Mar 20 15:34:54 python3[8940]: IP ARP Table for context management
Mar 20 15:34:54 python3[8940]: Total number of entries: 0
Mar 20 15:34:54 python3[8940]: Address         Age       MAC Address     Interface       Flags
Mar 20 15:34:54 python3[8940]: ---- {"command": "show ip interface vrf vpc-keepalive", "template": "show ip interface", "enable": true, "order": 128} ** changed : False  INFO
Mar 20 15:34:54 python3[8940]: IP Interface Status for VRF "vpc-keepalive"
Mar 20 15:34:54 python3[8940]: Vlan123, Interface status: protocol-up/link-up/admin-up, iod: 3,
Mar 20 15:34:54 python3[8940]:   IP address: 192.168.0.6, IP subnet: 192.168.0.4/30 route-preference: 0, tag: 0
Mar 20 15:34:54 python3[8940]:   IP broadcast address: 255.255.255.255
Mar 20 15:34:54 python3[8940]:   IP multicast groups locally joined: none
Mar 20 15:34:54 python3[8940]:   IP MTU: 1500 bytes (using link MTU)
Mar 20 15:34:54 python3[8940]:   IP primary address route-preference: 0, tag: 0
Mar 20 15:34:54 python3[8940]:   IP proxy ARP : disabled
Mar 20 15:34:54 python3[8940]:   IP Local Proxy ARP : disabled
Mar 20 15:34:54 python3[8940]:   IP multicast routing: disabled
Mar 20 15:34:54 python3[8940]:   IP icmp redirects: enabled
Mar 20 15:34:54 python3[8940]:   IP directed-broadcast: disabled
Mar 20 15:34:54 python3[8940]:   IP Forwarding: disabled
Mar 20 15:34:54 python3[8940]:   IP icmp unreachables (except port): disabled
Mar 20 15:34:54 python3[8940]:   IP icmp port-unreachable: enabled
Mar 20 15:34:54 python3[8940]:   IP unicast reverse path forwarding: none
Mar 20 15:34:54 python3[8940]:   IP load sharing: none
Mar 20 15:34:54 python3[8940]:   IP interface statistics last reset: never
Mar 20 15:34:54 python3[8940]:   IP interface software stats: (sent/received/forwarded/originated/consumed)
Mar 20 15:34:54 python3[8940]:     Unicast packets    : 44724215/44724215/0/44724215/89448430
Mar 20 15:34:54 python3[8940]:     Unicast bytes      : 4187500226/3382464332/0/4187500226/6764928664
Mar 20 15:34:54 python3[8940]:     Multicast packets  : 0/0/0/0/0
Mar 20 15:34:54 python3[8940]:     Multicast bytes    : 0/0/0/0/0
Mar 20 15:34:54 python3[8940]:     Broadcast packets  : 0/0/0/0/0
Mar 20 15:34:54 python3[8940]:     Broadcast bytes    : 0/0/0/0/0
Mar 20 15:34:54 python3[8940]:     Labeled packets    : 0/0/0/0/0
Mar 20 15:34:54 python3[8940]:     Labeled bytes      : 0/0/0/0/0
Mar 20 15:34:54 python3[8940]: ---- {"command": "show ip arp vrf vpc-keepalive", "template": "show ip arp", "enable": true, "order": 128} ** changed : False  INFO
Mar 20 15:34:54 python3[8940]: Flags: * - Adjacencies learnt on non-active FHRP router
Mar 20 15:34:54 python3[8940]:        + - Adjacencies synced via CFSoE
Mar 20 15:34:54 python3[8940]:        # - Adjacencies Throttled for Glean
Mar 20 15:34:54 python3[8940]:        CP - Added via L2RIB, Control plane Adjacencies
Mar 20 15:34:54 python3[8940]:        PS - Added via L2RIB, Peer Sync
Mar 20 15:34:54 python3[8940]:        RO - Re-Originated Peer Sync Entry
Mar 20 15:34:54 python3[8940]:        D - Static Adjacencies attached to down interface
Mar 20 15:34:54 python3[8940]: IP ARP Table for context vpc-keepalive
Mar 20 15:34:54 python3[8940]: Total number of entries: 1
Mar 20 15:34:54 python3[8940]: Address         Age       MAC Address     Interface       Flags
Mar 20 15:34:54 python3[8940]: 192.168.0.5   00:18:14  1c71.0d2b.1131  Vlan123
Mar 20 15:34:54 python3[8940]: ^^^^ END additional_tasks ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 20 15:34:54 python3[8940]: No Netmiko Cisco XR device found
Mar 20 15:34:54 python3[8940]: No Netmiko HPE Comware device found
Mar 20 15:34:54 python3[8940]: No Netmiko Linux device found
Mar 20 15:34:56 python3[9122]: An exception occurred: `ValidationError: '1c71.0d2b.1131' is not a 'ipv4'
Mar 20 15:34:56 python3[9122]: Failed validating 'format' in schema['properties']['address']:
Mar 20 15:34:56 python3[9122]:     {'format': 'ipv4', 'type': 'string'}
Mar 20 15:34:56 python3[9122]: On instance['address']:
Mar 20 15:34:56 python3[9122]:     '1c71.0d2b.1131'`
Mar 20 15:34:56 python3[9122]: ```
Mar 20 15:34:56 python3[9122]: Traceback (most recent call last):
Mar 20 15:34:56 python3[9122]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 20 15:34:56 python3[9122]:     script.output = script.run(data=data, commit=commit)
Mar 20 15:34:56 python3[9122]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 20 15:34:56 python3[9122]:     log_ingest(log)
Mar 20 15:34:56 python3[9122]:   File "/opt/netbox/venv/lib64/python3.8/site-packages/netdoc/utils.py", line 236, in log_ingest
Mar 20 15:34:56 python3[9122]:     module.ingest(log)
Mar 20 15:34:56 python3[9122]:   File "/opt/netbox/venv/lib64/python3.8/site-packages/netdoc/ingestors/netmiko_cisco_nxos_show_lldp_neighbors_detail.py", line 67, in ingest
Mar 20 15:34:56 python3[9122]:     remote_discoverable_list += discoverable.get_list(
Mar 20 15:34:56 python3[9122]:   File "/opt/netbox/venv/lib64/python3.8/site-packages/netdoc/schemas/discoverable.py", line 86, in get_list
Mar 20 15:34:56 python3[9122]:     validate(kwargs, get_schema(), format_checker=FormatChecker())
Mar 20 15:34:56 python3[9122]:   File "/opt/netbox/venv/lib64/python3.8/site-packages/jsonschema/validators.py", line 934, in validate
Mar 20 15:34:56 python3[9122]:     raise error
Mar 20 15:34:56 python3[9122]: jsonschema.exceptions.ValidationError: '1c71.0d2b.1131' is not a 'ipv4'
Mar 20 15:34:56 python3[9122]: Failed validating 'format' in schema['properties']['address']:
Mar 20 15:34:56 python3[9122]:     {'format': 'ipv4', 'type': 'string'}
Mar 20 15:34:56 python3[9122]: On instance['address']:
Mar 20 15:34:56 python3[9122]:     '1c71.0d2b.1131'
Mar 20 15:34:56 python3[9122]: ```
Mar 20 15:34:56 python3[9122]: Exception raised during script execution: '1c71.0d2b.1131' is not a 'ipv4'
Mar 20 15:34:56 python3[9122]: Failed validating 'format' in schema['properties']['address']:
Mar 20 15:34:56 python3[9122]:     {'format': 'ipv4', 'type': 'string'}
Mar 20 15:34:56 python3[9122]: On instance['address']:
Mar 20 15:34:56 python3[9122]:     '1c71.0d2b.1131'
```

**Comment by dainok** [comment]
If this a lab, can you provide me the entire log? You can download it in NetDoc -> Logs -> Download (top, right)

**Comment by svestenik** [comment]
![Logs _ NetBox](https://user-images.githubusercontent.com/33282479/226545643-6ea28f9b-5546-404c-ad03-532d39e62fa7.jpg)

Not able to locate Download link on the Logs page.

**Comment by dainok** [comment]
Download page is inside each log.
Can you type "show lldp neigh" from the nexus and drop here the line containing "1c71.0d2b.1131"? I guess the neighbor is reporting 1c71.0d2b.1131 as management IP address. If so, I have to implement an additional check.

**Comment by dainok** [comment]
Try 0.9.43

**Comment by svestenik** [comment]
Updated from repository, it does not throw the same error now, but still does not ingest the device. Two new error logs appear:
1. duplicate key value violates unique constraint "ipam_vrf_rd_key"
2. Exception raised during script execution: Device not attached to the Discoverable

[device not attached error.txt](https://github.com/dainok/netdoc/files/11049492/device.not.attached.error.txt)
[duplicate key value error.txt](https://github.com/dainok/netdoc/files/11049493/duplicate.key.value.error.txt)

I have attached raw output for both errors.

**Comment by svestenik** [comment]
And in both IOS and NX-OS case, no ingestion is happening after parsing.
![2023-03-23 11_21_43-Logs _ NetBox](https://user-images.githubusercontent.com/33282479/227175875-1012a9b3-ef4e-46d0-85c3-aa04cb6c7aa0.jpg)
![2023-03-23 11_21_14-Logs _ NetBox](https://user-images.githubusercontent.com/33282479/227175879-9937c6c8-cdd9-4bd4-8b71-ce8937e6f377.jpg)
[1783 (1).json.log](https://github.com/dainok/netdoc/files/11049716/1783.1.json.log)

[2012.json.log](https://github.com/dainok/netdoc/files/11049741/2012.json.log)

**Comment by dainok** [comment]
About (1) (VRF RD error) it happens when you have multiple VRF using the same RD. Is that your case?

About (2) (device not attached error) it happens when the discoverable is not attached to a device. The attached device is used by NetDoc to create objects under the right Device. Device shuold be created automatically when logs with order == 0 are parsed. I see from your screenshots that hostname logs are not ingested.

I'm asking to help me in debugging. you need to use this script: https://github.com/dainok/netdoc/blob/master/scripts/ingest.py

And run it inside a django shell:

/opt/netbox/venv/bin/python3 /opt/netbox/netbox/manage.py shell < yourdownloadedscript.py

The script start ingesting from order==0. Check if you get any errors.
The same if you go to Netbox -> Others -> Script -> NetDoc -> Ingest script.

**Comment by svestenik** [comment]
About (1) . There will be situations where same RD is configured for same VRF on several devices. 

I'll check about (2) and get back to you. In the meantime, I spotted another error when executing IOS discoverer:

[interface status error.txt](https://github.com/dainok/netdoc/files/11050213/interface.status.error.txt)

I guess it gets confused about interface status "deleted" which shows on certain versions of IOS once you remove subinterface.

[Interface deleted](https://user-images.githubusercontent.com/33282479/227191226-49a149b0-371a-4c21-ad99-883c4570bad2.jpg)

**Comment by dainok** [comment]
Can you test 0.9.44? (you need to migraate the DB)

**Comment by svestenik** [comment]
Regarding (2) (device not attached error), I've checked the log for hostname discovery. I think that script needs a bit of adjustment, since it parses every mention of word hostname from running-config. That word can be mentioned several times in several places, depending on the device config. In my case, it is used to identify the device to central logging server also.

[1609.json.log](https://github.com/dainok/netdoc/files/11050574/1609.json.log)
[parsing hostname](https://user-images.githubusercontent.com/33282479/227199257-e4efc7da-13a7-4fd8-adf3-51cceaf6a461.jpg)

**Comment by dainok** [comment]
I tested your log and it's working on my side. The regex is looking for hostname until the end of the line (not the conf). Then the word after hotsname is used as hostname.

Can you post the log 1779?

**Comment by svestenik** [comment]
Attaching log 1779.
[1779.json.log](https://github.com/dainok/netdoc/files/11050859/1779.json.log)
[log1779](https://user-images.githubusercontent.com/33282479/227207700-dd3e3312-4d89-417f-b2d4-f4040e9b0732.jpg)

**Comment by dainok** [comment]
Sorry for the obvious question: are you sure this is a Cisco Nexus switch?
The prompt "SomeSwitch-SW2#" should not be displayed in raw_output.

**Comment by svestenik** [comment]
Yes. It is a Nexus 3048 switch on NXOS version 7.0(3)I4. I have few dozen of them on the campus. 
If you want, I can execute against version 9 of NX-OS also ?

**Comment by dainok** [comment]
Would you please send me an email? (find my addrress at adainese.it)

**Comment by andyb2000** [comment]
I think I've solved the duplicate RD issue in pr I've just submitted #43

**Comment by dainok** [comment]
Just to clean up:
- NetDoc now check management IP, non ip are silently discarded)
- VRF with duplicated RD are created only if mandatory_rd=False (https://github.com/dainok/netdoc/commit/c5d419bb4e9ab963f4ec0ee5ce01e51d4015be1a)
- HOSTNAME not parsed has a diffenret issue.
