### ISSUE TITLE
[Issue] IOS parser script errors out on parsing interface speed

### ISSUE THREAD

**Issue by svestenik** [dainok/netdoc#38]
For the sake of keeping thing clean, opening up separate thread for IOS parser issues. Netdoc v 0.9.44, fresh install.
While trying to discover a CISCO2901 router running IOS 15.7-3, IOS parser errors out on parsing interface speed:

Mar 24 10:02:33 python3[76880]: An exception occurred: `ValueError: Invalid interface speed 1gbps`
Mar 24 10:02:33 python3[76880]: ```
Mar 24 10:02:33 python3[76880]: Traceback (most recent call last):
Mar 24 10:02:33 python3[76880]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 377, in normalize_interface_speed
Mar 24 10:02:33 python3[76880]:     speed = int(speed)
Mar 24 10:02:33 python3[76880]: ValueError: invalid literal for int() with base 10: '1gbps'
Mar 24 10:02:33 python3[76880]: The above exception was the direct cause of the following exception:
Mar 24 10:02:33 python3[76880]: Traceback (most recent call last):
Mar 24 10:02:33 python3[76880]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 24 10:02:33 python3[76880]:     script.output = script.run(data=data, commit=commit)
Mar 24 10:02:33 python3[76880]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 24 10:02:33 python3[76880]:     log_ingest(log)
Mar 24 10:02:33 python3[76880]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 237, in log_ingest
Mar 24 10:02:33 python3[76880]:     module.ingest(log)
Mar 24 10:02:33 python3[76880]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/ingestors/netmiko_cisco_ios_show_interfaces.py", line 21, in ingest
Mar 24 10:02:33 python3[76880]:     speed = utils.normalize_interface_speed(item.get("speed"))
Mar 24 10:02:33 python3[76880]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 379, in normalize_interface_speed
Mar 24 10:02:33 python3[76880]:     raise ValueError(f"Invalid interface speed {speed}") from exc
Mar 24 10:02:33 python3[76880]: ValueError: Invalid interface speed 1gbps
Mar 24 10:02:33 python3[76880]: ```
Mar 24 10:02:33 python3[76880]: Exception raised during script execution: Invalid interface speed 1gbps

[ios interface speed error.txt](https://github.com/dainok/netdoc/files/11060327/ios.interface.speed.error.txt)

**Comment by dainok** [comment]
Thank you, this is an easy fix but I need a couple of days. If you want:

1. Edit https://github.com/dainok/netdoc/blob/master/netdoc/utils.py
2. Duplicate line 374 adding `gbps` instead of `gb/s`
3. Restart the scheduler

**Comment by dainok** [comment]
Fixed by https://github.com/dainok/netdoc/pull/39
