### ISSUE TITLE
Cisco IOS LLDP neighbor with sub-int error

### ISSUE THREAD

**Issue by andyb2000** [dainok/netdoc#41]
This is a bit of a bug on various Cisco IOS editions that in the output of show lldp it includes a sub-interface, like this:

`------------------------------------------------
Local Intf: Gi0/0/2.1
Chassis id: d0c7.899c.aaaa
Port id: Gi1/0/49
Port Description: aaaa
System Name: aaaa
`
Which then causes a failure in cable.py because netbox will not accept a cable on a virtual interface "Cables cannot be terminated to Virtual interfaces"

Suggestion is in cable.py around line 82 to do a check if a colon or dot is present in left_interface_o or
right_interface_o and to skip adding if that is the case to avoid the error.

**Comment by svestenik** [comment]
Same issue appears on both CDP and LLDP NX-OS parsers.

**Comment by dainok** [comment]
I'm including a test like this: if local or remote interface is not physical, then skip.

Maybe I can use https://github.com/dainok/netdoc/blob/master/netdoc/utils.py (parent_interface(label):

~~~
# Pseudocode
if local_interface != parent_interface(local_interface) or remote_interface != parent_interface(remote_interface):
  # Skip subinterfaces
  continue
~~~

Better if you can test. I cannot do that before the weekend.

**Comment by andyb2000** [comment]
Makes sense. I've applied and tested on #44 and appears to work.

**Comment by dainok** [comment]
Thank you very much!
