### ISSUE TITLE
ImportError: cannot import name 'get_scripts' from 'extras.scripts' (/opt/netbox/netbox/extras/scripts.py)

### ISSUE THREAD

**Issue by schmitzkopf** [dainok/netdoc#47]
Hello - trying to implement Netdoc into an existing NetBox-Installation and I followed your guidelines, I just excluded the steps which I've already done with the official documentation part. 

My issue occurs when running the  "sudo -u netbox /opt/netbox/upgrade.sh" - it runs through until I get the error, mentioned in the title: "ImportError: cannot import name 'get_scripts' from 'extras.scripts' (/opt/netbox/netbox/extras/scripts.py)"

Any suggestion on what it could be? it's an Ubuntu 22.04 with only NetBox installed (no docker or anything) - only plugin I want or try to install is your NetDoc plugin.

Thanks in advance and best regards
<img width="444" alt="netdoc_issue" src="https://github.com/dainok/netdoc/assets/46482169/2b364514-cce0-45b6-9744-fbf4eebda728">

**Comment by dainok** [comment]
Hi @schmitzkopf, which NetBox version are you using? At the moment 3.4.10 is supported, later versions are not.

**Comment by schmitzkopf** [comment]
Hi @dainok - thank you very much for your fast response! I already thought about your input, but wanted to be sure...I was on 3.5.5 and now on 3.5.6, so I guess I have to "downgrade" to use your plugin. (Or do you might plan to make it available for newer versions too?) Thank you very much for your very great work!

**Comment by dainok** [comment]
Unfortunately 3.5 changed a lot, and I don't have a compatible release yet. I'm also not sure if you can downgrade
I have no ETA for the new version.

**Comment by schmitzkopf** [comment]
Good morning @dainok, many thanks again for your efforts. Not sure if I will install an old version, since downgrading is I guess not as easy as a fresh "old"-install. Again, thanks for your great work.

**Comment by mhabiballa** [comment]
Hi dainok :)
+1 same issue!
Hop fully it will be fixed on Netbox 3.5 +
