### ISSUE TITLE
Mikrotik support ?

### ISSUE THREAD

**Issue by svestenik** [dainok/netdoc#5]
Supported by Netmiko,
Templates already in NTC-templates project

As for the lab, I can set up something with different Mikrotik models if needed.

Platform supports CDP and LLDP for neighbor discovery.

**Comment by dainok** [comment]
@svestenik prepare a 2-node labs (see https://github.com/dainok/netdoc/tree/master/netdoc/tests/netmiko_cisco_ios/lab1) and let me know when you are ready. I'll explain how to export the config.

**Comment by dainok** [comment]
Timeout.

**Comment by svestenik** [comment]
I'll get to this as soon as I finish Ubiquity.
