### ISSUE TITLE
Ubiquity EdgeSwitch support ?

### ISSUE THREAD

**Issue by svestenik** [dainok/netdoc#6]
Limited support by Netmiko
Templates present in NTC-Templates

I can set up a lab with several different models if need be.

**Comment by dainok** [comment]
To add a new supported device, we need, at least:

- A 2 node lab (see https://github.com/dainok/netdoc/tree/master/netdoc/tests/netmiko_cisco_ios/lab1)
- Check if supported by Netmiko (see http://ktbyers.github.io/netmiko/PLATFORMS.html)
- List of commands
- Add missing NTC Templates (see https://github.com/networktocode/ntc-templates/tree/master/tests)

**Comment by dainok** [comment]
@svestenik prepare a 2-node labs (see https://github.com/dainok/netdoc/tree/master/netdoc/tests/netmiko_cisco_ios/lab1) and let me know when you are ready. I'll explain how to export the config.

**Comment by svestenik** [comment]
I'll prepare both labs starting next week and let you know.

**Comment by dainok** [comment]
@svestenik any update?

**Comment by svestenik** [comment]
Lab is ready, how do we proceed ?

**Comment by dainok** [comment]
I need you copy the exact output from commands in files:
- 1 output per file
- files are named MGMTIPADDRESS-the_show_command.raw
- files will be stored in the project, so replace data you consider sensitive
- at least 1 command must report the hostname
