### ISSUE TITLE
After uprade netdoc 3.5.3 module 'netdoc.topologies' has no attribute 'get__topology_data'

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#77]
After uprade netdoc 3.5.3, after connection has been discovered, create diagram having below issue, no issue on netdoc 0.10.33

<class 'AttributeError'>

module 'netdoc.topologies' has no attribute 'get__topology_data'

Python version: 3.10.12
NetBox version: 3.5.8
Plugins: 
  netdoc: 3.5.3

**Comment by dainok** [comment]
Confirmed, the form to create the Diagram is missing the "mode" field.
Something has changed in NetBox 3.5 and the line is not honored.

**Comment by dainok** [comment]
Forgive me: I commented a line and I don't remember why. My CI pipe should include web tests also, but don't have time to enhance it yet.

https://github.com/dainok/netdoc/pull/79 should fix the issue, please upgrade to 3.5.5 and let me know.

**Comment by dietybright** [comment]
The issue is fixed, thank alot @dainok
