### ISSUE TITLE
Discover PaloAlto "Invalid route type a oi"

### ISSUE THREAD

**Issue by proebstle** [dainok/netdoc#84]
<html>
<body>

An exception occurred: ValueError: Invalid route type a oiTraceback (most recent call last):   File "/opt/netbox-3.5.9/netbox/extras/scripts.py", line 504, in _run_script     script.output = script.run(data=data, commit=commit)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/opt/netbox-3.5.9/netbox/scripts/netdoc_scripts.py", line 353, in run     log_ingest(log)   File "/opt/netbox/venv/lib/python3.11/site-packages/netdoc/utils.py", line 578, in log_ingest     module.ingest(log)   File "/opt/netbox/venv/lib/python3.11/site-packages/netdoc/ingestors/xml_panw_ngfw_show_routing_route.py", line 34, in ingest     protocol = utils.normalize_route_type(item.get("flags"))                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/opt/netbox/venv/lib/python3.11/site-packages/netdoc/utils.py", line 988, in normalize_route_type     raise ValueError(f"Invalid route type {route_type}") ValueError: Invalid route type a oi
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by proebstle** [comment]
Closed

**Comment by dainok** [comment]
Fixed by https://github.com/dainok/netdoc/pull/85
