### ISSUE TITLE
Ingest Cisco XR inventory missing part-number

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#87]
Our Cisco XR NCS-5501-SE unable to ingest after discovered.

I have changed https://github.com/dainok/netdoc/blob/master/netdoc/ingestors/netmiko_cisco_xr_admin_show_inventory.py line 22 from item.get("name") to item.get("descr"), then it able to ingested.

Not sure if that is a typo.

**Comment by dainok** [comment]
Can you send me the log file?

**Comment by dietybright** [comment]
[193.json](https://github.com/dainok/netdoc/files/12864156/193.json)

FYI the exported log
