### ISSUE TITLE
Route type missing from case select

### ISSUE THREAD

**Issue by andyb2000** [dainok/netdoc#9]
User static routes:
U - per-user static route

Example on a Cisco ASR1000:
U        192.192.55.132/30 [1/0] via 192.168.1.1

(Typically these are from radius/dynamic routing protocols injecting per-user routes)
Just needs the normalize_route_type adding.
PR to follow.

**Comment by dainok** [comment]
If I get what "per-user" means, is a sort of temporary static route, correct?
A sorf of user-space static route.
I wonder if this route type deserve a dedicated type or not (just asking).

**Comment by andyb2000** [comment]
Fair question. Yes it's a temporary static route, mainly used in DSL/radius provided connections where the static is software defined rather than defined in the config.
I think define as static route since that's strictly the Cisco definition of it, though yes I agree it's questionable

**Comment by dainok** [comment]
Can you to add a new route type called `Userspace` (`u`)?
You also need to update `models.py`.
