### ISSUE TITLE
device discovery in netbox not working

### ISSUE THREAD

**Issue by alexandreseitz** [dainok/netdoc#9]
Hello 
I try to use your netbox plugin. Installation seems ok, migrations done.
Discovery seems to work on some Cisco devices, I can see logs results in netbox.
However, none of the logs have been "parsed" and "ingested".
I have tested it on ASR1002-X and IOS-XR.

Is there something to do to get data injected in netbox database.
No interfaces have been created
thanks for your help

**Comment by dainok** [comment]
Check this: https://github.com/dainok/netdoc/issues/5

**Comment by alexandreseitz** [comment]
Ok thanks, it works now.
