### ISSUE TITLE
Feature Request - Support Cisco ASA Devices

### ISSUE THREAD

**Issue by cmong-nextech** [dainok/netdoc#90]
It would be nice to have support for ASA devices in addition to the IOS, XE, XR, NXOS devices. Netmiko has an ASA module:
https://ktbyers.github.io/netmiko/docs/netmiko/cisco/cisco_asa_ssh.html

**Comment by dainok** [comment]
See https://github.com/dainok/netdoc/wiki/Developing-NetDoc#adding-support-for-new-devices
You are required to prepare a lab, then send me the output.

**Comment by cmong-nextech** [comment]
I have sent you an email with the data I have gathered. It looks like the only issue is with netdoc marking the output of the discovery command of the ASA devices as failed, thus not parsing or ingesting it.

**Comment by dietybright** [comment]
I am interested on ASA/FTD also, netmiko able to pulling information with device_type cisco_ftd_ssh

**Comment by dainok** [comment]
Please provide a lab and consider a sponsorship :)

**Comment by dainok** [comment]
Still interested? Can you provide the requested files?

**Comment by dainok** [comment]
No answer
