### ISSUE TITLE
Aruba IAP 305 Ingestion is failing

### ISSUE THREAD

**Issue by ismailkalolwala** [dainok/netdoc#91]
Discovery with NETMIKO HP PROCURVE looks to be working but ingestion is failing - screenshot is below 

![image](https://github.com/dainok/netdoc/assets/145698133/67eafd5a-b058-4830-9ec5-5fdbbb0cc2a8)

Requesting you to please review and assist.

**Comment by dainok** [comment]
I don't think you can use Procurve to parse Aruba IAP. Send me the log so I can check.

**Comment by ismailkalolwala** [comment]
![image](https://github.com/dainok/netdoc/assets/145698133/bc8c0e62-a2cd-4266-b33e-bdb97d3290ca)
![image](https://github.com/dainok/netdoc/assets/145698133/38469064-586b-477a-974a-70edb9f0455d)
![image](https://github.com/dainok/netdoc/assets/145698133/f337355e-5f53-4c71-8c32-06789a727198)
![image](https://github.com/dainok/netdoc/assets/145698133/db7ea5bc-6c5f-4d82-b632-26c1230531de)



Can you please advise if i can discover Aruba IAP wireless using NETBOX at this point of time.

**Comment by dainok** [comment]
To debug logs, please see https://github.com/dainok/netdoc/wiki/FAQ#netdoc-is-not-parsingingesting-data

**Comment by ismailkalolwala** [comment]
Not all but few commands are parsed with Aruba IAP 305

![image](https://github.com/dainok/netdoc/assets/145698133/b9db4de0-fa18-417f-b9c1-ffd6e3a49292)

and Ingestion is failing as mentioned in the above screenshots

**Comment by ismailkalolwala** [comment]
Can you please let me know how i can view the schedules for add discoverables and how can i delete them

**Comment by dainok** [comment]
Parsed = False means that data are not parsed, and this make sense because you are using procurve to parse Aruba.
As described in the FAQ https://github.com/dainok/netdoc/wiki/FAQ#netdoc-is-not-parsingingesting-data you need to check log by log.
