### ISSUE TITLE
Diagram dynamic/static issue

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#93]
When create diagram l2, with dynamic option, its keep floating, if choose static option, the connections between same devices stacked to each other. Any idea?

Another thing is whether netdoc supported connection label showing on the diagram?

**Comment by dainok** [comment]
When you use the static, you need to arrange your devices. Then you have to refresh. This is a limitation of the framework I used. If you know better open source framework, please write a note.
For the same reason connection labels are not supported.

**Comment by dietybright** [comment]
Thank @dainok , able to auto re-arrange cable after refresh page
