### ISSUE TITLE
pyVmomi ingest vm ip address

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#94]
From the log I saw pyVmomi able to discover vm ip address with key "guest_address". Is it able to ingest to Netbox with vm ip address?

**Comment by dainok** [comment]
No because it's missing the netmask/prefixlength (hope I can remember correctly).

**Comment by dietybright** [comment]
Got it, appreciated if you could ingest ip address with all /32 to netbox, it would be appeared to IPAM under major prefix, easy for tracking all IPAM at least

**Comment by dainok** [comment]
It's better to integrate a script polling operating system. Linux is already supported. The reason is that I don't want to ingest partial or wrong information to NetBox. But... you can implement custom scripts if you think that it's useful for you.

**Comment by dietybright** [comment]
Hi @dainok ,

With .guest.net, it can polling out data macaddress, ipaddress, prefixlength of each nic. I am not familar with coding, still try to explore the script, hope if you can have a look on it.

For exp:
>>> print(vm[38].guest.net)              
(vim.vm.GuestInfo.NicInfo) [
   (vim.vm.GuestInfo.NicInfo) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      network = '<omitted>',
      ipAddress = (str) [
         '192.168.x.136',
         'fe80::250:56ff:fe8a:6414'
      ],
      macAddress = '00:50:56:8a:64:14',
      connected = true,
      deviceConfigId = 4000,
      dnsConfig = <unset>,
      ipConfig = (vim.net.IpConfigInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         ipAddress = (vim.net.IpConfigInfo.IpAddress) [
            (vim.net.IpConfigInfo.IpAddress) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ipAddress = '192.168.x.136',
               prefixLength = 26,
               origin = <unset>,
               state = 'preferred',
               lifetime = <unset>
            },
            (vim.net.IpConfigInfo.IpAddress) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ipAddress = 'fe80::250:56ff:fe8a:6414',
               prefixLength = 64,
               origin = <unset>,
               state = 'unknown',
               lifetime = <unset>
            }
         ],
         dhcp = <unset>,
         autoConfigurationEnabled = <unset>
      },
      netBIOSConfig = <unset>
   },
   (vim.vm.GuestInfo.NicInfo) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      network = '<omitted>',
      ipAddress = (str) [
         '42.116.x.238',
         'fe80::250:56ff:fe8a:c5ab'
      ],
      macAddress = '00:50:56:8a:c5:ab',
      connected = true,
      deviceConfigId = 4001,
      dnsConfig = <unset>,
      ipConfig = (vim.net.IpConfigInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         ipAddress = (vim.net.IpConfigInfo.IpAddress) [
            (vim.net.IpConfigInfo.IpAddress) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ipAddress = '42.116.x.238',
               prefixLength = 29,
               origin = <unset>,
               state = 'preferred',
               lifetime = <unset>
            },
            (vim.net.IpConfigInfo.IpAddress) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ipAddress = 'fe80::250:56ff:fe8a:c5ab',
               prefixLength = 64,
               origin = <unset>,
               state = 'unknown',
               lifetime = <unset>
            }
         ],
         dhcp = <unset>,
         autoConfigurationEnabled = <unset>
      },
      netBIOSConfig = <unset>
   }
]

**Comment by dietybright** [comment]
Hi @dainok ,

I have modified your discovery pyvmomi script to get ipaddress and prefixmask, then ingest to netbox with data_vm_interface with value "address" but there is an issue "unexpected keyword arguments: 'address'".

Seem address of vm interface need to ingest under IPAM or something, would you mind to have a look?
