### ISSUE TITLE
ValueError: Invalid interface speed 10gigfd000

### ISSUE THREAD

**Issue by proebstle** [dainok/netdoc#97]
An exception occurred: ValueError: Invalid interface speed 10gigfd000

netdoc/utils.py
Please add: 
    speed = speed.replace("gigfd", "000") # HP Procurve

**Comment by proebstle** [comment]
https://github.com/dainok/netdoc/pull/98

**Comment by dainok** [comment]
Thank you @proebstle
Can you write down the interface speed from "show interface"? I wonder why it's replaced with 10gigfd000

**Comment by proebstle** [comment]
![image](https://github.com/dainok/netdoc/assets/65938262/360ecd6d-0d4d-4345-b5ba-68f8afa0ea23)

**Comment by proebstle** [comment]
Again: An exception occurred: ValueError: Invalid interface speed 10gigfd000
[10804.json](https://github.com/dainok/netdoc/files/13060346/10804.json)

**Comment by dainok** [comment]
There is an issue on CI/CD, so the commit has not been integrated into PIP package. Are you using netdoc from git master or from pip?

**Comment by dainok** [comment]
@proebstle please check https://github.com/dainok/netdoc/releases/tag/3.5.11 and let me know

**Comment by proebstle** [comment]
Solved with new version

**Comment by proebstle** [comment]
solved
